CREATE DATABASE IF NOT EXISTS simulado;
use simulado;

CREATE TABLE IF NOT EXISTS Clientes (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Concessionarias (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Veiculos (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  modelo VARCHAR(100) NOT NULL,
  preco text NOT NULL
);

CREATE TABLE IF NOT EXISTS Vendas (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  id_cliente INT,
  id_veiculo INT,
  id_concessionaria INT,
  FOREIGN KEY (id_cliente) REFERENCES Clientes (id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (id_veiculo) REFERENCES Veiculos (id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (id_concessionaria) REFERENCES Concessionarias (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Alocacao (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  area INT NOT NULL,
  id_veiculo INT,
  id_concessionaria INT,
  quantidade INT NOT NULL,
  FOREIGN KEY (id_veiculo) REFERENCES Veiculos (id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (id_concessionaria) REFERENCES Concessionarias (id) ON DELETE SET NULL ON UPDATE CASCADE
);